"""record who added a tin

Revision ID: 0e13d0e50a82
Revises: 375a7ef657d2
Create Date: 2026-08-26 23:29:17.133102

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0e13d0e50a82"
down_revision: str | None = "375a7ef657d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock_item", sa.Column("added_by_id", sa.UUID(), nullable=True))
    # Named explicitly. Autogenerate emits None here, which Postgres auto-names on
    # creation — and then downgrade's drop_constraint(None, ...) has nothing to drop, so
    # it raises, the transaction rolls back, and the migration is quietly irreversible.
    op.create_foreign_key(
        "fk_stock_item_added_by_id",
        "stock_item",
        "user_account",
        ["added_by_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # Backfill from the ledger. The opening `purchase` event already records who put the
    # tin on the shelf, so existing rows do not have to stay null — and a feed that says
    # "somebody added a tin" for every tin predating this column would be useless.
    op.execute(
        """
        UPDATE stock_item
        SET added_by_id = (
            SELECT e.user_id
            FROM stock_event e
            WHERE e.stock_item_id = stock_item.id AND e.kind = 'purchase'
            ORDER BY e.occurred_at ASC
            LIMIT 1
        )
        WHERE added_by_id IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_stock_item_added_by_id", "stock_item", type_="foreignkey")
    op.drop_column("stock_item", "added_by_id")
    # ### end Alembic commands ###
