"""catalog: brands, ingredients, teas

Revision ID: 19a59e81be9e
Revises: 28716d5edfb8
Create Date: 2026-08-26 20:28:31.130806

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "19a59e81be9e"
down_revision: str | None = "28716d5edfb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand",
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("country", sa.String(length=60), nullable=True),
        sa.Column("website", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "ingredient",
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "leaf",
                "herb",
                "flower",
                "spice",
                "fruit",
                "other",
                name="ingredient_category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_caffeinated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "tea",
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=True),
        sa.Column(
            "tea_type",
            sa.Enum(
                "green",
                "black",
                "oolong",
                "puerh",
                "white",
                "herbal",
                "rooibos",
                "blend",
                name="tea_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "caffeine_level",
            sa.Enum(
                "none",
                "low",
                "medium",
                "high",
                name="caffeine_level",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="medium",
            nullable=False,
        ),
        sa.Column("origin_country", sa.String(length=60), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("brew_temp_c", sa.Integer(), nullable=True),
        sa.Column("brew_seconds", sa.Integer(), nullable=True),
        sa.Column("grams_per_100ml", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("is_approved", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("brew_seconds IS NULL OR brew_seconds > 0", name="ck_brew_seconds"),
        sa.CheckConstraint(
            "brew_temp_c IS NULL OR brew_temp_c BETWEEN 40 AND 100", name="ck_brew_temp"
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brand.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["user_account.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("ix_tea_approved_type", "tea", ["is_approved", "tea_type"], unique=False)
    op.create_table(
        "tea_ingredient",
        sa.Column("tea_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.Column("percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "percentage IS NULL OR (percentage > 0 AND percentage <= 100)",
            name="ck_ingredient_percentage",
        ),
        sa.ForeignKeyConstraint(["ingredient_id"], ["ingredient.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tea_id"], ["tea.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tea_id", "ingredient_id"),
    )
    op.create_index(
        "ix_tea_ingredient_ingredient_id", "tea_ingredient", ["ingredient_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tea_ingredient_ingredient_id", table_name="tea_ingredient")
    op.drop_table("tea_ingredient")
    op.drop_index("ix_tea_approved_type", table_name="tea")
    op.drop_table("tea")
    op.drop_table("ingredient")
    op.drop_table("brand")
    # ### end Alembic commands ###
