"""friendships

Revision ID: 375a7ef657d2
Revises: f5c157d51cce
Create Date: 2026-08-26 23:28:29.127325

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "375a7ef657d2"
down_revision: str | None = "f5c157d51cce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friendship",
        sa.Column("user_a_id", sa.UUID(), nullable=False),
        sa.Column("user_b_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "blocked",
                name="friendship_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("requested_by_id", sa.UUID(), nullable=True),
        sa.Column("blocked_by_id", sa.UUID(), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'blocked') = (blocked_by_id IS NOT NULL)",
            name="ck_friendship_block_has_blocker",
        ),
        sa.CheckConstraint("user_a_id < user_b_id", name="ck_friendship_canonical_order"),
        sa.ForeignKeyConstraint(["blocked_by_id"], ["user_account.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["requested_by_id"], ["user_account.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_a_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_b_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_a_id", "user_b_id", name="uq_friendship_pair"),
    )
    op.create_index("ix_friendship_user_b", "friendship", ["user_b_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_friendship_user_b", table_name="friendship")
    op.drop_table("friendship")
    # ### end Alembic commands ###
