"""shop coordinates

Revision ID: 84525f527756
Revises: f64a3ed243f0
Create Date: 2026-08-27 11:05:36.438795

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "84525f527756"
down_revision: str | None = "f64a3ed243f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shop", sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column("shop", sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column("shop", sa.Column("geocoded_at", sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        "ck_shop_latitude_range", "shop", "latitude IS NULL OR (latitude BETWEEN -90 AND 90)"
    )
    op.create_check_constraint(
        "ck_shop_longitude_range", "shop", "longitude IS NULL OR (longitude BETWEEN -180 AND 180)"
    )
    op.create_check_constraint(
        "ck_shop_pin_is_complete", "shop", "(latitude IS NULL) = (longitude IS NULL)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_shop_pin_is_complete", "shop", type_="check")
    op.drop_constraint("ck_shop_longitude_range", "shop", type_="check")
    op.drop_constraint("ck_shop_latitude_range", "shop", type_="check")
    op.drop_column("shop", "geocoded_at")
    op.drop_column("shop", "longitude")
    op.drop_column("shop", "latitude")
    # ### end Alembic commands ###
