"""favourites, shop reviews, brewing notes

Revision ID: a33972124c4a
Revises: d2010cf318be
Create Date: 2026-08-27 14:29:56.511012

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a33972124c4a"
down_revision: str | None = "d2010cf318be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brewing_note",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tea_id", sa.UUID(), nullable=False),
        sa.Column("brew_temp_c", sa.Integer(), nullable=True),
        sa.Column("brew_seconds", sa.Integer(), nullable=True),
        sa.Column("grams_per_100ml", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "brew_seconds IS NULL OR brew_seconds > 0", name="ck_brewing_note_seconds"
        ),
        sa.CheckConstraint(
            "brew_temp_c IS NOT NULL OR brew_seconds IS NOT NULL "
            "OR grams_per_100ml IS NOT NULL OR note IS NOT NULL",
            name="ck_brewing_note_not_empty",
        ),
        sa.CheckConstraint(
            "brew_temp_c IS NULL OR brew_temp_c BETWEEN 40 AND 100", name="ck_brewing_note_temp"
        ),
        sa.ForeignKeyConstraint(["tea_id"], ["tea.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "tea_id"),
    )
    op.create_table(
        "favourite_shop",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("shop_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["shop_id"], ["shop.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "shop_id"),
    )
    op.create_index("ix_favourite_shop_user", "favourite_shop", ["user_id"], unique=False)
    op.create_table(
        "favourite_tea",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tea_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tea_id"], ["tea.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "tea_id"),
    )
    op.create_index("ix_favourite_tea_user", "favourite_tea", ["user_id"], unique=False)
    op.create_table(
        "shop_review",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("shop_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("score >= 1 AND score <= 10", name="ck_shop_review_score_range"),
        sa.ForeignKeyConstraint(["shop_id"], ["shop.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "shop_id", name="uq_shop_review_user_shop"),
    )
    op.create_index(
        "ix_shop_review_shop_created", "shop_review", ["shop_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_shop_review_shop_created", table_name="shop_review")
    op.drop_table("shop_review")
    op.drop_index("ix_favourite_tea_user", table_name="favourite_tea")
    op.drop_table("favourite_tea")
    op.drop_index("ix_favourite_shop_user", table_name="favourite_shop")
    op.drop_table("favourite_shop")
    op.drop_table("brewing_note")
    # ### end Alembic commands ###
