"""households, members, invites, stock ledger

Revision ID: b21f6d655855
Revises: 19a59e81be9e
Create Date: 2026-08-26 21:38:34.824713

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b21f6d655855"
down_revision: str | None = "19a59e81be9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "household",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["user_account.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "household_invite",
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("invited_email", sa.String(length=320), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["accepted_by_id"], ["user_account.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["user_account.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["household_id"], ["household.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        "ix_household_invite_household_id", "household_invite", ["household_id"], unique=False
    )
    op.create_table(
        "household_member",
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner", "member", name="member_role", native_enum=False, create_constraint=True
            ),
            server_default="member",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["household_id"], ["household.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("household_id", "user_id"),
    )
    op.create_index("ix_household_member_user_id", "household_member", ["user_id"], unique=False)
    op.create_table(
        "stock_item",
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("tea_id", sa.UUID(), nullable=False),
        sa.Column(
            "quantity_grams", sa.Numeric(precision=8, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "low_stock_grams", sa.Numeric(precision=8, scale=2), server_default="10", nullable=False
        ),
        sa.Column("location", sa.String(length=120), nullable=True),
        sa.Column("opened_at", sa.Date(), nullable=True),
        sa.Column("best_before", sa.Date(), nullable=True),
        sa.Column("purchased_at", sa.Date(), nullable=True),
        sa.Column("price_paid_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("low_stock_grams >= 0", name="ck_stock_low_threshold_non_negative"),
        sa.CheckConstraint(
            "price_paid_minor IS NULL OR currency IS NOT NULL", name="ck_stock_price_has_currency"
        ),
        sa.CheckConstraint("quantity_grams >= 0", name="ck_stock_quantity_non_negative"),
        sa.ForeignKeyConstraint(["household_id"], ["household.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tea_id"], ["tea.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_stock_item_household_id", "stock_item", ["household_id"], unique=False)
    op.create_table(
        "stock_event",
        sa.Column("stock_item_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "purchase",
                "brew",
                "adjust",
                "discard",
                name="stock_event_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("delta_grams", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("delta_grams <> 0", name="ck_stock_event_non_zero"),
        sa.ForeignKeyConstraint(["stock_item_id"], ["stock_item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_stock_event_item_occurred",
        "stock_event",
        ["stock_item_id", "occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_event_item_occurred", table_name="stock_event")
    op.drop_table("stock_event")
    op.drop_index("ix_stock_item_household_id", table_name="stock_item")
    op.drop_table("stock_item")
    op.drop_index("ix_household_member_user_id", table_name="household_member")
    op.drop_table("household_member")
    op.drop_index("ix_household_invite_household_id", table_name="household_invite")
    op.drop_table("household_invite")
    op.drop_table("household")
    # ### end Alembic commands ###
