"""user profile fields

Revision ID: d2010cf318be
Revises: 84525f527756
Create Date: 2026-08-27 12:04:12.210174

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d2010cf318be"
down_revision: str | None = "84525f527756"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_account", sa.Column("pronouns", sa.String(length=40), nullable=True))
    op.add_column("user_account", sa.Column("bio", sa.Text(), nullable=True))
    op.add_column("user_account", sa.Column("location", sa.String(length=120), nullable=True))
    op.add_column(
        "user_account",
        sa.Column(
            "favourite_tea_type",
            sa.Enum(
                "green",
                "black",
                "oolong",
                "puerh",
                "white",
                "herbal",
                "rooibos",
                "blend",
                name="tea_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "favourite_tea_type")
    op.drop_column("user_account", "location")
    op.drop_column("user_account", "bio")
    op.drop_column("user_account", "pronouns")
    # ### end Alembic commands ###
