"""ingredient ratings

Revision ID: f2fba3cff616
Revises: a33972124c4a
Create Date: 2026-08-27 17:51:42.033056

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f2fba3cff616"
down_revision: str | None = "a33972124c4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredient_rating",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("score >= 1 AND score <= 10", name="ck_ingredient_rating_score_range"),
        sa.ForeignKeyConstraint(["ingredient_id"], ["ingredient.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "ingredient_id"),
    )
    op.create_index("ix_ingredient_rating_user", "ingredient_rating", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ingredient_rating_user", table_name="ingredient_rating")
    op.drop_table("ingredient_rating")
    # ### end Alembic commands ###
