"""reviews

Revision ID: f5c157d51cce
Revises: b21f6d655855
Create Date: 2026-08-26 23:02:39.200863

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f5c157d51cce"
down_revision: str | None = "b21f6d655855"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tea_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("aroma", sa.Integer(), nullable=True),
        sa.Column("flavour", sa.Integer(), nullable=True),
        sa.Column("aftertaste", sa.Integer(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("brewed_at", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "aftertaste IS NULL OR (aftertaste >= 1 AND aftertaste <= 10)",
            name="ck_review_aftertaste_range",
        ),
        sa.CheckConstraint(
            "aroma IS NULL OR (aroma >= 1 AND aroma <= 10)", name="ck_review_aroma_range"
        ),
        sa.CheckConstraint(
            "flavour IS NULL OR (flavour >= 1 AND flavour <= 10)", name="ck_review_flavour_range"
        ),
        sa.CheckConstraint("score >= 1 AND score <= 10", name="ck_review_score_range"),
        sa.ForeignKeyConstraint(["tea_id"], ["tea.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "tea_id", name="uq_review_user_tea"),
    )
    op.create_index("ix_review_tea_created", "review", ["tea_id", "created_at"], unique=False)
    op.create_index("ix_review_user_id", "review", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_user_id", table_name="review")
    op.drop_index("ix_review_tea_created", table_name="review")
    op.drop_table("review")
    # ### end Alembic commands ###
