"""shops, listings, purchases and images

Revision ID: f64a3ed243f0
Revises: 0e13d0e50a82
Create Date: 2026-08-27 09:40:05.856342

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f64a3ed243f0"
down_revision: str | None = "0e13d0e50a82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop",
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("country", sa.String(length=60), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("is_approved", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "website IS NOT NULL OR address IS NOT NULL OR city IS NOT NULL",
            name="ck_shop_reachable_somehow",
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["user_account.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("ix_shop_approved_city", "shop", ["is_approved", "city"], unique=False)
    op.create_table(
        "shop_listing",
        sa.Column("shop_id", sa.UUID(), nullable=False),
        sa.Column("tea_id", sa.UUID(), nullable=False),
        sa.Column("pack_grams", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("price_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("product_url", sa.String(length=500), nullable=True),
        sa.Column("is_available", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("pack_grams IS NULL OR pack_grams > 0", name="ck_listing_pack_positive"),
        sa.CheckConstraint(
            "price_minor IS NULL OR currency IS NOT NULL", name="ck_listing_price_has_currency"
        ),
        sa.CheckConstraint(
            "price_minor IS NULL OR price_minor >= 0", name="ck_listing_price_non_negative"
        ),
        sa.ForeignKeyConstraint(["shop_id"], ["shop.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tea_id"], ["tea.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "shop_id",
            "tea_id",
            "pack_grams",
            name="uq_listing_shop_tea_pack",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index("ix_shop_listing_tea_id", "shop_listing", ["tea_id"], unique=False)
    op.add_column("household", sa.Column("image_url", sa.String(length=500), nullable=True))
    op.add_column("stock_event", sa.Column("shop_id", sa.UUID(), nullable=True))
    op.add_column("stock_event", sa.Column("price_paid_minor", sa.Integer(), nullable=True))
    op.add_column("stock_event", sa.Column("currency", sa.String(length=3), nullable=True))
    op.create_foreign_key(
        "fk_stock_event_shop_id", "stock_event", "shop", ["shop_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("stock_item", sa.Column("shop_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_stock_item_shop_id", "stock_item", "shop", ["shop_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_stock_item_shop_id", "stock_item", type_="foreignkey")
    op.drop_column("stock_item", "shop_id")
    op.drop_constraint("fk_stock_event_shop_id", "stock_event", type_="foreignkey")
    op.drop_column("stock_event", "currency")
    op.drop_column("stock_event", "price_paid_minor")
    op.drop_column("stock_event", "shop_id")
    op.drop_column("household", "image_url")
    op.drop_index("ix_shop_listing_tea_id", table_name="shop_listing")
    op.drop_table("shop_listing")
    op.drop_index("ix_shop_approved_city", table_name="shop")
    op.drop_table("shop")
    # ### end Alembic commands ###
