"""Starter catalog. Real teas and real ingredients, so the app is never empty."""

# (name, category, is_caffeinated)
INGREDIENTS: list[tuple[str, str, bool]] = [
    # leaves
    ("Green tea leaf", "leaf", True),
    ("Black tea leaf", "leaf", True),
    ("Oolong tea leaf", "leaf", True),
    ("White tea leaf", "leaf", True),
    ("Pu-erh tea leaf", "leaf", True),
    ("Matcha", "leaf", True),
    ("Yerba mate", "leaf", True),
    ("Rooibos", "leaf", False),
    ("Honeybush", "leaf", False),
    # herbs
    ("Peppermint", "herb", False),
    ("Spearmint", "herb", False),
    ("Lemongrass", "herb", False),
    ("Lemon balm", "herb", False),
    ("Chamomile", "herb", False),
    ("Nettle", "herb", False),
    ("Lemon verbena", "herb", False),
    # flowers
    ("Jasmine flower", "flower", False),
    ("Lavender", "flower", False),
    ("Hibiscus", "flower", False),
    ("Rose petal", "flower", False),
    ("Elderflower", "flower", False),
    ("Osmanthus", "flower", False),
    ("Blue cornflower", "flower", False),
    # spices
    ("Cinnamon", "spice", False),
    ("Cardamom", "spice", False),
    ("Ginger", "spice", False),
    ("Clove", "spice", False),
    ("Star anise", "spice", False),
    ("Black pepper", "spice", False),
    ("Vanilla", "spice", False),
    ("Fennel seed", "spice", False),
    ("Liquorice root", "spice", False),
    # fruit
    ("Orange peel", "fruit", False),
    ("Lemon peel", "fruit", False),
    ("Apple piece", "fruit", False),
    ("Rosehip", "fruit", False),
    ("Bergamot oil", "fruit", False),
    ("Mango piece", "fruit", False),
    # other
    ("Toasted rice", "other", False),
]

# (name, country, website)
BRANDS: list[tuple[str, str | None, str | None]] = [
    ("Ahmad Tea", "United Kingdom", "https://www.ahmadtea.com"),
    ("Twinings", "United Kingdom", "https://www.twinings.co.uk"),
    ("Kusmi Tea", "France", "https://www.kusmitea.com"),
    ("Dammann Frères", "France", "https://www.dammann.fr"),
    ("Dilmah", "Sri Lanka", "https://www.dilmahtea.com"),
    ("Palais des Thés", "France", "https://www.palaisdesthes.com"),
    ("Yunnan Sourcing", "China", "https://yunnansourcing.com"),
]

# Brewing defaults by tea type: (temp_c, seconds, grams per 100 ml)
BREWING: dict[str, tuple[int, int, float]] = {
    "green": (80, 120, 1.0),
    "black": (95, 180, 1.0),
    "oolong": (90, 150, 1.5),
    "white": (75, 180, 1.0),
    "puerh": (95, 120, 1.5),
    "herbal": (100, 300, 1.5),
    "rooibos": (100, 300, 1.5),
    "blend": (95, 180, 1.0),
}

# (name, tea_type, caffeine, brand, origin, description, [(ingredient, pct, primary)])
TEAS: list[
    tuple[str, str, str, str | None, str | None, str, list[tuple[str, float | None, bool]]]
] = [
    (
        "Earl Grey",
        "black",
        "high",
        "Twinings",
        "India",
        "Black tea scented with bergamot — the archetypal afternoon cup.",
        [("Black tea leaf", 95.0, True), ("Bergamot oil", 5.0, True)],
    ),
    (
        "English Breakfast",
        "black",
        "high",
        "Twinings",
        "India",
        "A brisk malty blend built to stand up to milk.",
        [("Black tea leaf", 100.0, True)],
    ),
    (
        "Lady Grey",
        "black",
        "high",
        "Twinings",
        "India",
        "Earl Grey softened with citrus peel and cornflower.",
        [
            ("Black tea leaf", 90.0, True),
            ("Bergamot oil", 3.0, False),
            ("Orange peel", 4.0, False),
            ("Lemon peel", 2.0, False),
            ("Blue cornflower", 1.0, False),
        ],
    ),
    (
        "Masala Chai",
        "black",
        "high",
        "Ahmad Tea",
        "India",
        "Assam base with the full spice cabinet. Brew strong, add milk.",
        [
            ("Black tea leaf", 60.0, True),
            ("Cinnamon", 10.0, True),
            ("Cardamom", 10.0, True),
            ("Ginger", 10.0, False),
            ("Clove", 5.0, False),
            ("Black pepper", 5.0, False),
        ],
    ),
    (
        "Sencha",
        "green",
        "medium",
        "Palais des Thés",
        "Japan",
        "Steamed Japanese green tea: grassy, marine, a little sweet.",
        [("Green tea leaf", 100.0, True)],
    ),
    (
        "Gunpowder Green",
        "green",
        "medium",
        "Dilmah",
        "China",
        "Rolled pellets that unfurl into a smoky, robust green.",
        [("Green tea leaf", 100.0, True)],
    ),
    (
        "Jasmine Pearls",
        "green",
        "medium",
        "Yunnan Sourcing",
        "China",
        "Hand-rolled pearls scented over fresh jasmine blossom.",
        [("Green tea leaf", 92.0, True), ("Jasmine flower", 8.0, True)],
    ),
    (
        "Ceremonial Matcha",
        "green",
        "high",
        "Palais des Thés",
        "Japan",
        "Stone-ground shade-grown leaf. Whisked, not steeped.",
        [("Matcha", 100.0, True)],
    ),
    (
        "Genmaicha",
        "green",
        "medium",
        "Dilmah",
        "Japan",
        "Green tea with toasted rice — nutty, savoury, forgiving.",
        [("Green tea leaf", 70.0, True), ("Toasted rice", 30.0, True)],
    ),
    (
        "Moroccan Mint",
        "green",
        "medium",
        "Ahmad Tea",
        "Morocco",
        "Gunpowder green and spearmint. Traditionally very sweet.",
        [("Green tea leaf", 70.0, True), ("Spearmint", 30.0, True)],
    ),
    (
        "Tie Guan Yin",
        "oolong",
        "medium",
        "Yunnan Sourcing",
        "China",
        "Iron Goddess of Mercy: orchid-floral, endlessly re-steepable.",
        [("Oolong tea leaf", 100.0, True)],
    ),
    (
        "Milk Oolong",
        "oolong",
        "medium",
        "Kusmi Tea",
        "Taiwan",
        "Creamy and buttery in the cup, with no dairy anywhere near it.",
        [("Oolong tea leaf", 100.0, True)],
    ),
    (
        "Shou Pu-erh",
        "puerh",
        "medium",
        "Yunnan Sourcing",
        "China",
        "Ripened and fermented: earthy, dark, mellow with age.",
        [("Pu-erh tea leaf", 100.0, True)],
    ),
    (
        "Silver Needle",
        "white",
        "low",
        "Palais des Thés",
        "China",
        "Nothing but unopened buds. Delicate, honeyed, easy to over-brew.",
        [("White tea leaf", 100.0, True)],
    ),
    (
        "Elderflower White",
        "white",
        "low",
        "Kusmi Tea",
        "China",
        "White tea lifted with elderflower and a little rose.",
        [("White tea leaf", 88.0, True), ("Elderflower", 8.0, True), ("Rose petal", 4.0, False)],
    ),
    (
        "Chamomile Dream",
        "herbal",
        "none",
        "Ahmad Tea",
        None,
        "Chamomile and lavender. The one you reach for at eleven at night.",
        [("Chamomile", 75.0, True), ("Lavender", 15.0, True), ("Lemon balm", 10.0, False)],
    ),
    (
        "Peppermint Leaf",
        "herbal",
        "none",
        "Ahmad Tea",
        None,
        "Straight peppermint. Sharp, cooling, good after dinner.",
        [("Peppermint", 100.0, True)],
    ),
    (
        "Hibiscus Cooler",
        "herbal",
        "none",
        "Dammann Frères",
        None,
        "Tart and ruby-red. Excellent iced.",
        [
            ("Hibiscus", 55.0, True),
            ("Rosehip", 25.0, True),
            ("Orange peel", 15.0, False),
            ("Apple piece", 5.0, False),
        ],
    ),
    (
        "Lemongrass Ginger",
        "herbal",
        "none",
        "Dilmah",
        "Sri Lanka",
        "Bright lemongrass with a warming ginger finish.",
        [("Lemongrass", 60.0, True), ("Ginger", 30.0, True), ("Lemon peel", 10.0, False)],
    ),
    (
        "Fennel Anise Calm",
        "herbal",
        "none",
        "Dammann Frères",
        None,
        "Sweet, liquorice-leaning, traditionally drunk for digestion.",
        [("Fennel seed", 45.0, True), ("Star anise", 30.0, True), ("Liquorice root", 25.0, False)],
    ),
    (
        "Rooibos Vanilla",
        "rooibos",
        "none",
        "Kusmi Tea",
        "South Africa",
        "Red bush and vanilla — naturally caffeine-free and never bitter.",
        [("Rooibos", 90.0, True), ("Vanilla", 10.0, True)],
    ),
    (
        "Honeybush Orange",
        "rooibos",
        "none",
        "Kusmi Tea",
        "South Africa",
        "Honeybush with citrus peel. Softer and sweeter than rooibos.",
        [("Honeybush", 85.0, True), ("Orange peel", 15.0, True)],
    ),
    (
        "Yerba Mate Verde",
        "herbal",
        "high",
        "Palais des Thés",
        "Argentina",
        "Unsmoked mate: vegetal, bracing, the strongest thing on this list.",
        [("Yerba mate", 100.0, True)],
    ),
]
