# Generated by Django 5.1.3 on 2025-02-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herbatka", "0002_alter_shop_img_url_alter_tea_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="location",
        ),
        migrations.AddField(
            model_name="shop",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
