# Generated by Django 5.1.3 on 2025-02-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herbatka", "0004_shop_email_shop_number_shop_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="shop",
            name="country",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="shop",
            name="number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="postal_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="shop",
            name="state",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="shop",
            name="street",
            field=models.CharField(max_length=255),
        ),
    ]
