# Generated by Django 5.1.3 on 2025-02-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "herbatka",
            "0005_alter_shop_city_alter_shop_country_alter_shop_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
