# Generated by Django 5.1.3 on 2025-02-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herbatka", "0006_alter_shop_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tea",
            name="tea_ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="teas", to="herbatka.teaingredient"
            ),
        ),
        migrations.AlterField(
            model_name="teaingredient",
            name="img_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
