# Generated by Django 5.1.3 on 2025-02-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herbatka", "0007_alter_tea_tea_ingredients_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teaqualityassignment",
            name="values",
        ),
        migrations.AddField(
            model_name="teaqualityassignment",
            name="value",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
