# Generated by Django 5.1.3 on 2025-02-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herbatka", "0008_remove_teaqualityassignment_values_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teaingredient",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
