# Generated by Django 5.1.3 on 2025-02-08 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("herbatka", "0009_alter_teaingredient_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tea",
            old_name="shop",
            new_name="shop_id",
        ),
        migrations.RenameField(
            model_name="teaqualityassignment",
            old_name="tea",
            new_name="tea_id",
        ),
        migrations.RenameField(
            model_name="teaqualityassignment",
            old_name="tea_quality",
            new_name="tea_quality_id",
        ),
    ]
