# Generated by Django 5.1.3 on 2025-05-17 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herbatka", "0014_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeaConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumptions",
                        to="herbatka.tearating",
                    ),
                ),
                (
                    "tea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumptions",
                        to="herbatka.tea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tea_consumptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-consumed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "consumed_at"],
                        name="herbatka_te_user_id_771f0b_idx",
                    ),
                    models.Index(
                        fields=["tea", "consumed_at"],
                        name="herbatka_te_tea_id_5dda3c_idx",
                    ),
                ],
            },
        ),
    ]
