# Generated by Django 5.1.3 on 2025-05-17 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("herbatka", "0015_teaconsumption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teaconsumption",
            name="rating",
        ),
    ]
