# Generated by Django 5.1.3 on 2025-05-17 23:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herbatka", "0016_remove_teaconsumption_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="url",
            new_name="website_url",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="city",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="country",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="number",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="state",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="street",
        ),
        migrations.AddField(
            model_name="shop",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shop",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="last_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="img_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ShopAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="herbatka.shop",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Shop addresses",
                "ordering": ["-is_primary", "city", "street"],
            },
        ),
    ]
