import re
import unicodedata

# term (folded, accent-free) -> canonical English name.
# Keys are French, Polish and English; the value is the name Herbatka already uses where one
# exists, and plain English otherwise.
LEXICON: dict[str, str] = {
    # --- tea bases
    "the noir": "Black tea leaf",
    "herbata czarna": "Black tea leaf",
    "czarna herbata": "Black tea leaf",
    "black tea": "Black tea leaf",
    "czarnej herbaty": "Black tea leaf",
    "the vert": "Green tea leaf",
    "herbata zielona": "Green tea leaf",
    "zielona herbata": "Green tea leaf",
    "green tea": "Green tea leaf",
    "zielonej herbaty": "Green tea leaf",
    "the blanc": "White tea leaf",
    "herbata biala": "White tea leaf",
    "biala herbata": "White tea leaf",
    "white tea": "White tea leaf",
    "the oolong": "Oolong tea leaf",
    "oolong": "Oolong tea leaf",
    "wulong": "Oolong tea leaf",
    "the pu erh": "Pu-erh tea leaf",
    "pu erh": "Pu-erh tea leaf",
    "puerh": "Pu-erh tea leaf",
    "matcha": "Matcha",
    "rooibos": "Rooibos",
    "czerwonokrzew": "Rooibos",
    "honeybush": "Honeybush",
    "mate": "Yerba mate",
    "yerba": "Yerba mate",
    # --- citrus & peel
    "bergamote": "Bergamot oil",
    "bergamotka": "Bergamot oil",
    "bergamot": "Bergamot oil",
    "ecorces d orange": "Orange peel",
    "ecorce d orange": "Orange peel",
    "zeste d orange": "Orange peel",
    "skorka pomaranczy": "Orange peel",
    "plasterki pomaranczy": "Orange peel",
    "orange peel": "Orange peel",
    "orange peels": "Orange peel",
    "pomarancza": "Orange peel",
    "fleur d oranger": "Orange blossom",
    "orange blossom": "Orange blossom",
    "kwiat pomaranczy": "Orange blossom",
    "citron": "Lemon peel",
    "skorka cytryny": "Lemon peel",
    "cytryna": "Lemon peel",
    "lemon peel": "Lemon peel",
    "lemon peels": "Lemon peel",
    "pamplemousse": "Grapefruit peel",
    "grejpfrut": "Grapefruit peel",
    "grapefruit": "Grapefruit peel",
    "citron vert": "Lime peel",
    "limonka": "Lime peel",
    "lime": "Lime peel",
    "mandarine": "Mandarin peel",
    "mandarin": "Mandarin peel",
    "mandarynka": "Mandarin peel",
    # --- herbs
    "citronnelle": "Lemongrass",
    "trawa cytrynowa": "Lemongrass",
    "lemongrass": "Lemongrass",
    "verveine": "Lemon verbena",
    "werbena": "Lemon verbena",
    "lemon verbena": "Lemon verbena",
    "melisse": "Lemon balm",
    "melisa": "Lemon balm",
    "lemon balm": "Lemon balm",
    "menthe poivree": "Peppermint",
    "mieta pieprzowa": "Peppermint",
    "peppermint": "Peppermint",
    "menthe verte": "Spearmint",
    "mieta zielona": "Spearmint",
    "spearmint": "Spearmint",
    "menthe": "Peppermint",
    "mieta": "Peppermint",
    "mint": "Peppermint",
    "ortie": "Nettle",
    "pokrzywa": "Nettle",
    "nettle": "Nettle",
    "tulsi": "Tulsi",
    "bazylia": "Tulsi",
    "camomille": "Chamomile",
    "rumianek": "Chamomile",
    "chamomile": "Chamomile",
    # --- flowers
    "bleuet": "Blue cornflower",
    "chaber": "Blue cornflower",
    "cornflower": "Blue cornflower",
    "rose": "Rose petal",
    "roza": "Rose petal",
    "rose petal": "Rose petal",
    "rose petals": "Rose petal",
    "jasmin": "Jasmine flower",
    "jasmin kwiat": "Jasmine flower",
    "jasmine": "Jasmine flower",
    "osmanthus": "Osmanthus",
    "lavande": "Lavender",
    "lawenda": "Lavender",
    "lavender": "Lavender",
    "sureau": "Elderflower",
    "czarny bez": "Elderflower",
    "elderflower": "Elderflower",
    "baie de sureau": "Elderberry",
    "elderberry": "Elderberry",
    "elderberries": "Elderberry",
    "hibiscus": "Hibiscus",
    "hibiskus": "Hibiscus",
    "kwiat hibiskusa": "Hibiscus",
    "souci": "Calendula petal",
    "calendula": "Calendula petal",
    "nagietek": "Calendula petal",
    "tournesol": "Sunflower petal",
    "sunflower": "Sunflower petal",
    "slonecznik": "Sunflower petal",
    "mauve": "Mallow flower",
    "malwa": "Mallow flower",
    "mallow": "Mallow flower",
    # --- spices
    "gingembre": "Ginger",
    "imbir": "Ginger",
    "ginger": "Ginger",
    "cannelle": "Cinnamon",
    "cynamon": "Cinnamon",
    "cinnamon": "Cinnamon",
    "cassia": "Cassia bark",
    "cassia bark": "Cassia bark",
    "girofle": "Clove",
    "gozdzik": "Clove",
    "clove": "Clove",
    "cloves": "Clove",
    "cardamome": "Cardamom",
    "kardamon": "Cardamom",
    "cardamom": "Cardamom",
    "poivre": "Black pepper",
    "pieprz": "Black pepper",
    "pepper": "Black pepper",
    "curcuma": "Turmeric root",
    "kurkuma": "Turmeric root",
    "turmeric": "Turmeric root",
    "reglisse": "Liquorice root",
    "lukrecja": "Liquorice root",
    "liquorice": "Liquorice root",
    "licorice": "Liquorice root",
    "anis etoile": "Star anise",
    "badiane": "Star anise",
    "anyz gwiazdkowy": "Star anise",
    "star anise": "Star anise",
    "anis": "Aniseed",
    "anyz": "Aniseed",
    "aniseed": "Aniseed",
    "fenouil": "Fennel seed",
    "koper": "Fennel seed",
    "fennel": "Fennel seed",
    "coriandre": "Coriander seed",
    "kolendra": "Coriander seed",
    "coriander": "Coriander seed",
    "vanille": "Vanilla",
    "wanilia": "Vanilla",
    "vanilla": "Vanilla",
    # --- fruit, nut, seed
    "cacao": "Cocoa nib",
    "kakao": "Cocoa nib",
    "cocoa": "Cocoa nib",
    "chocolat": "Cocoa nib",
    "czekolada": "Cocoa nib",
    "chocolate": "Cocoa nib",
    "amande": "Almond",
    "migdal": "Almond",
    "almond": "Almond",
    "noix de coco": "Coconut",
    "kokos": "Coconut",
    "coconut": "Coconut",
    "pomme": "Apple piece",
    "jablko": "Apple piece",
    "apple": "Apple piece",
    "mangue": "Mango piece",
    "mango": "Mango piece",
    "eglantier": "Rosehip",
    "cynorhodon": "Rosehip",
    "dzika roza": "Rosehip",
    "rosehip": "Rosehip",
    "rosehips": "Rosehip",
    "genievre": "Juniper berry",
    "jalowiec": "Juniper berry",
    "juniper": "Juniper berry",
    "goji": "Goji berry",
    "argousier": "Sea buckthorn",
    "rokitnik": "Sea buckthorn",
    "sea buckthorn": "Sea buckthorn",
    "fraise": "Strawberry piece",
    "truskawka": "Strawberry piece",
    "strawberry": "Strawberry piece",
    "framboise": "Raspberry piece",
    "malina": "Raspberry piece",
    "raspberry": "Raspberry piece",
    "mure": "Blackberry",
    "jezyna": "Blackberry",
    "blackberry": "Blackberry",
    "cassis": "Blackcurrant",
    "czarna porzeczka": "Blackcurrant",
    "blackcurrant": "Blackcurrant",
    "ananas": "Pineapple piece",
    "pineapple": "Pineapple piece",
    "papaye": "Papaya piece",
    "papaja": "Papaya piece",
    "papaya": "Papaya piece",
    "peche": "Peach piece",
    "brzoskwinia": "Peach piece",
    "peach": "Peach piece",
    "sumac": "Sumac berry",
    # --- grains & roots
    "chicoree": "Chicory root",
    "cykoria": "Chicory root",
    "chicory": "Chicory root",
    "salsepareille": "Sarsaparilla root",
    "sarsaparilla": "Sarsaparilla root",
    "saule": "Willow bark",
    "wierzba": "Willow bark",
    "willow": "Willow bark",
    "orge": "Barley",
    "jeczmien": "Barley",
    "barley": "Barley",
    "sarrasin": "Buckwheat",
    "gryka": "Buckwheat",
    "buckwheat": "Buckwheat",
    "riz souffle": "Puffed rice",
    "puffed rice": "Puffed rice",
    "riz grille": "Toasted rice",
    "ryz": "Toasted rice",
    "rice": "Toasted rice",
    # --- terms the first pass missed, from the unmapped report
    "cynorrhodon": "Rosehip",
    "owoc dzikiej rozy": "Rosehip",
    "caroube": "Carob",
    "carob": "Carob",
    "szarancza": "Carob",
    "murier": "Mulberry leaf",
    "mulberry": "Mulberry leaf",
    "morwa": "Mulberry leaf",
    "carotte": "Carrot",
    "carrot": "Carrot",
    "marchew": "Carrot",
    "moringa": "Moringa",
    "betterave": "Beetroot",
    "beetroot": "Beetroot",
    "burak": "Beetroot",
    "datte": "Date piece",
    "date": "Date piece",
    "daktyl": "Date piece",
    "galanga": "Galangal",
    "galangal": "Galangal",
    "sucre": "Sugar",
    "sugar": "Sugar",
    "cukier": "Sugar",
    "guarana": "Guarana",
    "ginseng": "Ginseng",
    "zenszen": "Ginseng",
    "eucalyptus": "Eucalyptus",
    "eukaliptus": "Eucalyptus",
    "thym": "Thyme",
    "thyme": "Thyme",
    "tymianek": "Thyme",
    "sauge": "Sage",
    "sage": "Sage",
    "szalwia": "Sage",
    "romarin": "Rosemary",
    "rosemary": "Rosemary",
    "rozmaryn": "Rosemary",
    "tilleul": "Linden flower",
    "linden": "Linden flower",
    "lipa": "Linden flower",
    "aubepine": "Hawthorn",
    "hawthorn": "Hawthorn",
    "glog": "Hawthorn",
    "figue": "Fig piece",
    "fig": "Fig piece",
    "figa": "Fig piece",
    "cerise": "Cherry piece",
    "cherry": "Cherry piece",
    "wisnia": "Cherry piece",
    "myrtille": "Blueberry",
    "blueberry": "Blueberry",
    "borowka": "Blueberry",
    "aronia": "Aronia berry",
    "aronie": "Aronia berry",
    "sumak": "Sumac berry",
    "abricot": "Apricot piece",
    "apricot": "Apricot piece",
    "morela": "Apricot piece",
    "poire": "Pear piece",
    "pear": "Pear piece",
    "gruszka": "Pear piece",
    "cranberry": "Cranberry",
    "canneberge": "Cranberry",
    "zurawina": "Cranberry",
    "kiwi": "Kiwi piece",
    "pasteque": "Watermelon piece",
    "watermelon": "Watermelon piece",
    "arbuz": "Watermelon piece",
    "acai": "Acai berry",
    "acerola": "Acerola",
    "spiruline": "Spirulina",
    "spirulina": "Spirulina",
    "carthame": "Safflower petal",
    "safflower": "Safflower petal",
    "krokosz": "Safflower petal",
    "ashwagandha": "Ashwagandha",
    "camellia sinensis": "Tea flower",
    "banane": "Banana piece",
    "banana": "Banana piece",
    "banan": "Banana piece",
    "melon": "Melon piece",
    "grenade": "Pomegranate",
    "pomegranate": "Pomegranate",
    "granat": "Pomegranate",
    # Polish inflects nouns, so these keys are stems: "truskawki", "truskawek" and
    # "truskawka" are the same berry and a singular key matches none of the other two.
    "truskaw": "Strawberry piece",
    "malin": "Raspberry piece",
    "jezyn": "Blackberry",
    "porzeczk": "Blackcurrant",
    "wisni": "Cherry piece",
    "gruszk": "Pear piece",
    "jablk": "Apple piece",
    "morel": "Apricot piece",
    "borowk": "Blueberry",
    "zurawin": "Cranberry",
    "brzoskwin": "Peach piece",
    "kozieradka": "Fenugreek",
    "fenugreek": "Fenugreek",
    "fenugrec": "Fenugreek",
    "stevia": "Stevia",
    "stewia": "Stevia",
    "trawa": "Lemongrass",
    "platki": "Petals",
    # --- German (Ronnefeldt)
    "schwarzer tee": "Black tea leaf",
    "schwarztee": "Black tea leaf",
    "gruner tee": "Green tea leaf",
    "gruntee": "Green tea leaf",
    "weisser tee": "White tea leaf",
    "weisstee": "White tea leaf",
    "pfefferminze": "Peppermint",
    "krauseminze": "Spearmint",
    "minze": "Peppermint",
    "kamille": "Chamomile",
    "fenchel": "Fennel seed",
    "sternanis": "Star anise",
    "sussholz": "Liquorice root",
    "lakritz": "Liquorice root",
    "ingwer": "Ginger",
    "zimt": "Cinnamon",
    "nelken": "Clove",
    "gewurznelken": "Clove",
    "kardamom": "Cardamom",
    "pfeffer": "Black pepper",
    "koriander": "Coriander seed",
    "kummel": "Caraway seed",
    "caraway": "Caraway seed",
    "hagebutte": "Rosehip",
    "apfel": "Apple piece",
    "orangenschale": "Orange peel",
    "zitronenschale": "Lemon peel",
    "zitronengras": "Lemongrass",
    "lemongras": "Lemongrass",
    "brennnessel": "Nettle",
    "brennessel": "Nettle",
    "lavendel": "Lavender",
    "ringelblume": "Calendula petal",
    "kornblume": "Blue cornflower",
    "sonnenblume": "Sunflower petal",
    "rosenblut": "Rose petal",
    "jasminblut": "Jasmine flower",
    "mandel": "Almond",
    "erdbeer": "Strawberry piece",
    "himbeer": "Raspberry piece",
    "brombeer": "Blackberry",
    "holunder": "Elderflower",
    "sanddorn": "Sea buckthorn",
    "zichorie": "Chicory root",
    "gerste": "Barley",
    "karotte": "Carrot",
    "rote bete": "Beetroot",
    "sussdolde": "Sweet cicely",
    "malve": "Mallow flower",
    "birne": "Pear piece",
    "pfirsich": "Peach piece",
    "aprikose": "Apricot piece",
    "heidelbeer": "Blueberry",
    # --- Czech (Oxalis)
    "cerny caj": "Black tea leaf",
    "zeleny caj": "Green tea leaf",
    "bily caj": "White tea leaf",
    "polodlouhy caj": "Oolong tea leaf",
    "mata": "Peppermint",
    "hermanek": "Chamomile",
    "fenykl": "Fennel seed",
    "badyan": "Star anise",
    "lekorice": "Liquorice root",
    "zazvor": "Ginger",
    "skorice": "Cinnamon",
    "hrebicek": "Clove",
    "sipek": "Rosehip",
    "ibisek": "Hibiscus",
    "pomerancov": "Orange peel",
    "citronov": "Lemon peel",
    "citronova trava": "Lemongrass",
    "medunka": "Lemon balm",
    "kopriva": "Nettle",
    "levandule": "Lavender",
    "mesicek": "Calendula petal",
    "chrpa": "Blue cornflower",
    "slunecnice": "Sunflower petal",
    "ruze": "Rose petal",
    "ruzov": "Rose petal",
    "vanilka": "Vanilla",
    "mandle": "Almond",
    "jahod": "Strawberry piece",
    "ostruzin": "Blackberry",
    "cerny bez": "Elderflower",
    "rakytnik": "Sea buckthorn",
    "cekanka": "Chicory root",
    "jecmen": "Barley",
    "mrkev": "Carrot",
    "repa": "Beetroot",
    "hruska": "Pear piece",
    "brusinka": "Cranberry",
    "boruvka": "Blueberry",
    "pepr": "Black pepper",
    "koriandr": "Coriander seed",
    # --- Dutch (Simon Lévelt)
    "zwarte thee": "Black tea leaf",
    "groene thee": "Green tea leaf",
    "witte thee": "White tea leaf",
    "pepermunt": "Peppermint",
    "venkel": "Fennel seed",
    "anijs": "Aniseed",
    "steranijs": "Star anise",
    "zoethout": "Liquorice root",
    "gember": "Ginger",
    "kaneel": "Cinnamon",
    "kruidnagel": "Clove",
    "kardemom": "Cardamom",
    "rozenbottel": "Rosehip",
    "sinaasappelschil": "Orange peel",
    "citroenschil": "Lemon peel",
    "citroengras": "Lemongrass",
    "citroenmelisse": "Lemon balm",
    "brandnetel": "Nettle",
    "goudsbloem": "Calendula petal",
    "korenbloem": "Blue cornflower",
    "zonnebloem": "Sunflower petal",
    "jasmijn": "Jasmine flower",
    "amandel": "Almond",
    "aardbei": "Strawberry piece",
    "framboos": "Raspberry piece",
    "braam": "Blackberry",
    "vlierbes": "Elderberry",
    "vlierbloesem": "Elderflower",
    "duindoorn": "Sea buckthorn",
    "cichorei": "Chicory root",
    "gerst": "Barley",
    "rijst": "Toasted rice",
    "biet": "Beetroot",
    "peer": "Pear piece",
    "appel": "Apple piece",
    "abrikoos": "Apricot piece",
    "bosbes": "Blueberry",
    "peper": "Black pepper",
    # --- German terms the first pass missed
    "zucker": "Sugar",
    "zitronenverbene": "Lemon verbena",
    "zitronenmyrte": "Lemon myrtle",
    "farberdistel": "Safflower petal",
    "nelke": "Clove",
    "korinthen": "Currant",
    "kirschstuck": "Cherry piece",
    "orangensaft": "Orange peel",
    "reismehl": "Rice flour",
    "holunderbeere": "Elderberry",
    "weissdorn": "Hawthorn",
    "lindenblute": "Linden flower",
    "salbei": "Sage",
    "thymian": "Thyme",
    "rosmarin": "Rosemary",
    "eibisch": "Mallow flower",
    "sussholzwurzel": "Liquorice root",
    "physalis": "Physalis",
    "lowenzahn": "Dandelion",
    "pissenlit": "Dandelion",
    "mniszek": "Dandelion",
    "orangenstuck": "Orange peel",
    "ruhrkraut": "Cudweed flower",
    # --- Czech terms the first pass missed
    "cukr": "Sugar",
    "rozinky": "Raisin",
    "rozinka": "Raisin",
    "raisin": "Raisin",
    "cerveny rybiz": "Redcurrant",
    "cerny rybiz": "Blackcurrant",
    "rybiz": "Blackcurrant",
    "visne": "Cherry piece",
    "kopretina": "Chamomile",
    "pomeranc": "Orange peel",
    "hrozny": "Grape piece",
    # Czech stems, for the same reason as the Polish ones above.
    "chrp": "Blue cornflower",
    "slez": "Mallow flower",
    "merunk": "Apricot piece",
    "ruz": "Rose petal",
    "svestk": "Plum piece",
    "trezalka": "St John's wort",
    "hrusk": "Pear piece",
    "meloun": "Melon piece",
    "brusink": "Cranberry",
    "borovnic": "Blueberry",
    "jerabin": "Rowan berry",
    "salvej": "Sage",
    "tymian": "Thyme",
    "materidouska": "Wild thyme",
    "lipov": "Linden flower",
    "boruvk": "Blueberry",
    "santalove drevo": "Sandalwood",
    "vres": "Heather flower",
    "svetlice": "Safflower petal",
    "laskavec": "Amaranth",
    "tea flower": "Tea flower",
    "lemon myrtle": "Lemon myrtle",
    "lemonmyrtle": "Lemon myrtle",
    "butterfly pea": "Butterfly pea flower",
    "blue pea": "Butterfly pea flower",
    "anchan": "Butterfly pea flower",
    "divizna": "Mullein flower",
    "mullein": "Mullein flower",
    "pandan": "Pandan leaf",
    "kaffir": "Kaffir lime leaf",
    "gyokuro": "Green tea leaf",
    "sencha": "Green tea leaf",
    "hojicha": "Green tea leaf",
    "genmaicha": "Green tea leaf",
    "bancha": "Green tea leaf",
    "kukicha": "Green tea leaf",
    # --- Swedish (Johan & Nyström)
    "svart te": "Black tea leaf",
    "gront te": "Green tea leaf",
    "vitt te": "White tea leaf",
    "mynta": "Peppermint",
    "kamomill": "Chamomile",
    "ingefara": "Ginger",
    "kanel": "Cinnamon",
    "kryddnejlika": "Clove",
    "nejlika": "Clove",
    "kardemumma": "Cardamom",
    "apelsin": "Orange peel",
    "citronmeliss": "Lemon balm",
    "citronskal": "Lemon peel",
    "jordgubb": "Strawberry piece",
    "hallon": "Raspberry piece",
    "blabar": "Blueberry",
    "tranbar": "Cranberry",
    "svarta vinbar": "Blackcurrant",
    "nypon": "Rosehip",
    "lakrits": "Liquorice root",
    "fankal": "Fennel seed",
    "gurkmeja": "Turmeric root",
    "vanilj": "Vanilla",
    "nassla": "Nettle",
    "solros": "Sunflower petal",
    "blaklint": "Blue cornflower",
    # --- Spanish (Tea Connection)
    "te negro": "Black tea leaf",
    "te verde": "Green tea leaf",
    "te blanco": "White tea leaf",
    "menta": "Peppermint",
    "hierbabuena": "Spearmint",
    "manzanilla": "Chamomile",
    "jengibre": "Ginger",
    "canela": "Cinnamon",
    "clavo de olor": "Clove",
    "cardamomo": "Cardamom",
    "limon": "Lemon peel",
    "naranja": "Orange peel",
    "manzana": "Apple piece",
    "fresa": "Strawberry piece",
    "frutilla": "Strawberry piece",
    "frambuesa": "Raspberry piece",
    "arandano": "Blueberry",
    "lavanda": "Lavender",
    "regaliz": "Liquorice root",
    "hinojo": "Fennel seed",
    "vainilla": "Vanilla",
    "ortiga": "Nettle",
    "escaramujo": "Rosehip",
    "hibisco": "Hibiscus",
    "cedron": "Lemon verbena",
    "maracuya": "Passionfruit",
    "pina": "Pineapple piece",
    "almendra": "Almond",
    "petalos de rosa": "Rose petal",
    # --- Finnish (Nordqvist)
    "musta tee": "Black tea leaf",
    "vihrea tee": "Green tea leaf",
    "valkoinen tee": "White tea leaf",
    "minttu": "Peppermint",
    "kamomilla": "Chamomile",
    "inkivaari": "Ginger",
    "kaneli": "Cinnamon",
    "neilikka": "Clove",
    "sitruunamelissa": "Lemon balm",
    "sitruuna": "Lemon peel",
    "appelsiini": "Orange peel",
    "omena": "Apple piece",
    "mansikka": "Strawberry piece",
    "vadelma": "Raspberry piece",
    "mustikka": "Blueberry",
    "karpalo": "Cranberry",
    "mustaherukka": "Blackcurrant",
    "ruusunmarja": "Rosehip",
    "ruusu": "Rose petal",
    "laventeli": "Lavender",
    "lakritsi": "Liquorice root",
    "fenkoli": "Fennel seed",
    "vanilja": "Vanilla",
    "nokkonen": "Nettle",
    "kehakukka": "Calendula petal",
    "sitruunaruoho": "Lemongrass",
    "dobromysl": "Oregano",
    "oregano": "Oregano",
    "tuzebnik": "Meadowsweet",
    "laskavcovky": "Amaranth",
    "vetvicky": "Twigs",
}

# Decorating adjectives ("biologische", "pravý", "getrocknete") need no entries: matching is
# substring-based, so "Biologische Rooibos" still finds "rooibos". They must never be mapped
# to "" either — keys are tried longest-first, so such an entry would beat the real
# ingredient and resolve the whole term to nothing.

#: Origin countries and additives ride along inside ingredient fields but name no plant.
NOT_AN_INGREDIENT = re.compile(
    r"(?i)^(?:inde|chine|japon|ceylan|kenya|india|china|japan|indie|chiny|japonia|"
    r"acidifiant|acide citrique|regulator kwasowosci|kwas cytrynowy|citric acid|"
    r"farine de riz|huiles? essentielles?|antyzbrylacz|emulgator|"
    r"e\d{3}\b|sprinkles|glazing agent|stabilisers?|stabilizator|colours?|colors?|"
    r"anti[- ]caking|carnauba|gum arabic|titanium dioxide|anthocyanins|curcumin|"
    r"barwnik|substancja|przeciwzbrylajaca|"
    r"voda|water|wasser|\w*ov[yaé] olej|rostlinny olej|sonnenblumeno?l|zonnebloemolie|"
    r"biologisch\w*|kartonov\w* obal|obal\b|verpakking|verpackung|"
    r"huile de tournesol|olej\b|oil\b)\b"
)

#: Terms that name no ingredient. `arome`/`aromat`/`flavouring` is the important one: a
#: regulated label says it for every flavoured tea, so as a feature it appears everywhere
#: and separates nothing. See analysis/data/README.md — this is the Twinings finding.
NOISE = re.compile(
    r"(?i)^(?:ar[oô]m\w*|aromat\w*|nat[uü]rlich\w*\s+arom\w*|natural(?:ny)?\s+ar[oô]?mes?|"
    r"natural flavou?ring|flavou?ring|"
    r"flavou?r|ar[oô]mes? naturels?|aromaty|naturalny aromat|extraits?|inne)\b"
)

KEYS = sorted(LEXICON, key=len, reverse=True)


#: NFD does not decompose these — they are distinct letters, not accented ones — so without
#: this line "jabłko" folds to "jab ko" and never matches "jablko".
UNDECOMPOSABLE = str.maketrans({"ł": "l", "Ł": "l", "ø": "o", "đ": "d", "ß": "ss"})


def fold(text: str) -> str:
    plain = "".join(
        c
        for c in unicodedata.normalize("NFD", text.casefold().translate(UNDECOMPOSABLE))
        if unicodedata.category(c) != "Mn"
    )
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9 ]+", " ", plain)).strip()


def to_english(term: str) -> str:
    folded = fold(term)
    return next((LEXICON[k] for k in KEYS if k in folded), "")


FLAVOURING_ANYWHERE = re.compile(r"(?i)arom\w*|flavou?ring|ascorbinsaure|ascorbic")


def is_noise(term: str) -> bool:
    folded = fold(term)
    return bool(
        NOISE.match(folded) or NOT_AN_INGREDIENT.match(folded) or FLAVOURING_ANYWHERE.search(folded)
    )


PERCENT = re.compile(r"\(?\s*(\d+(?:[.,]\d+)?)\s*%\s*\)?")
SPLIT = re.compile(r"[,;•·]|\bet\b|\band\b|\boraz\b|\bi\b(?=\s)|\bund\b|\ben\b(?=\s)|\ba\b(?=\s)")


def parse(raw: str) -> list[tuple[str, str]]:
    parts = []
    for chunk in SPLIT.split(raw):
        chunk = chunk.strip(" .·:;()")
        if sum(c.isalpha() for c in chunk) < 3:
            continue
        pct = ""
        m = PERCENT.search(chunk)
        if m:
            pct = m.group(1).replace(",", ".")
            chunk = PERCENT.sub(" ", chunk).strip()
        chunk = re.sub(r"\s*\([^)]*\)\s*", " ", chunk).strip(" .·:;")
        if chunk:
            parts.append((chunk, pct))
    return parts
